# Generated by Django 5.2.10 on 2026-02-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0006_add_contract_timestamp_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        db_index=True, help_text="Transaction hash", max_length=64
                    ),
                ),
                (
                    "caller",
                    models.CharField(
                        db_index=True,
                        help_text="Source account address (G...)",
                        max_length=56,
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        db_index=True,
                        help_text="Contract function name",
                        max_length=128,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        help_text="Function parameters in XDR-encoded form"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Function result in XDR-encoded form",
                        null=True,
                    ),
                ),
                (
                    "ledger_sequence",
                    models.PositiveBigIntegerField(
                        db_index=True, help_text="Ledger sequence number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="contractevent",
            new_name="ingest_cont_contrac_3666e0_idx",
            old_name="ingest_cont_contrac_timest_idx",
        ),
        migrations.AddField(
            model_name="contractinvocation",
            name="contract",
            field=models.ForeignKey(
                help_text="Target contract invoked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invocations",
                to="ingest.trackedcontract",
            ),
        ),
        migrations.AddField(
            model_name="contractevent",
            name="invocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Invocation that generated this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="ingest.contractinvocation",
            ),
        ),
        migrations.AddIndex(
            model_name="contractevent",
            index=models.Index(
                fields=["invocation"], name="ingest_cont_invocat_123230_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractinvocation",
            index=models.Index(
                fields=["contract", "created_at"], name="ingest_cont_contrac_76d989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractinvocation",
            index=models.Index(fields=["caller"], name="ingest_cont_caller_1d11a7_idx"),
        ),
        migrations.AddIndex(
            model_name="contractinvocation",
            index=models.Index(
                fields=["tx_hash"], name="ingest_cont_tx_hash_c37f09_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractinvocation",
            constraint=models.UniqueConstraint(
                fields=("tx_hash", "contract"), name="unique_tx_hash_contract"
            ),
        ),
    ]
