# Generated by Django 5.2.10 on 2026-02-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0007_contractinvocation_and_more"),
        ("ingest", "0009_contractevent_payload_gin"),
    ]

    operations = [
    ]
