# Generated by Django 5.2.10 on 2026-03-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0018_merge_deprecation_and_eventdedup"),
        ("ingest", "0018_merge_webhook_timeout_and_eventdedup"),
    ]

    operations = []
